### ISSUE TITLE
nxtalkproxyd doesn't grab `NXTALKPROXYD_ADDRREMOTE` variable from `docker-compose.yml`

### ISSUE THREAD

**Issue by zeigerpuppy** [pojntfx/nextcloud-talk-jitsi-bot#9]
I have tried building and launching the docker container.
However, when running, I get the following error:

```
nxtalkproxyd      | {"level":"info","error":"Get \"https://mynetxcloud.com/ocs/v2.php/apps/spreed/api/v1/room\": dial tcp: lookup mynetxcloud.com on xxx.xxx.xxx.xxx:53: no such host","timestamp":"2020-05-19T04:16:02Z","message":"could not read rooms, retrying"}
```
(IP address of DNS cache removed in log for security)

It looks like the container is trying to connect to the default nextcloud instance: https://mynetxcloud.com

my docker-compose file contains the following environment variable definitions:

```yaml
        environment:
            NXTALKPROXYD_DBPATH: "/var/lib/nxtalkproxyd"
            NXTALKPROXYD_USERNAME: "jitsibot"
            NXTALKPROXYD_PASSWORD: "<PASSWORD>"
            NXTALKPROXYD_ADDRREMOTE: "https://nextcloud.server.net"
            NCTALKPROXYD_ADDRLOCAL:: "https://nxtalkproxyd:1696"
```
